# Generated by Django 4.1.3 on 2022-12-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meal_Id', models.TextField(max_length=500)),
                ('Name', models.TextField(max_length=500)),
                ('Catagory', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('Veg_Non', models.TextField(max_length=500)),
                ('Nutrient', models.TextField(max_length=500)),
                ('Disease', models.TextField(max_length=500)),
                ('Diet', models.TextField(max_length=500)),
                ('Price', models.TextField(max_length=500)),
            ],
        ),
    ]
